on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Проверка форматирования на соответствие PEP8
    steps:
      - uses: actions/checkout@v4
      - name: Установить black
        run: pip install black
      - name: Проверка форматирования
        run: |
          # Проверяем изменения в текущем пулл-реквесте
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' | xargs black --check -l120 --skip-string-normalization
